on:
  push:
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ]
        python: ["3.12", ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          cache: true
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          pdm install

      - name: Cache YoWASP build products
        uses: actions/cache@v4
        with:
          path: ~/.cache/YoWASP
          key: YoWASP-${{ runner.os }}-${{ hashFiles('./.venv/**/*.wasm') }}
          restore-keys: |
            YoWASP-${{ runner.os }}-

      - name: Run tests
        run: |
          make sim-build
          (timeout 30 make sim-run || true) 2> sim.log
          grep "Booting Zephyr OS build" sim.log
